import os

ENERGIA_ENTRENAMIENTO = 8
MIN_AUMENTO_EXPERIENCIA = 20
MAX_AUMENTO_EXPERIENCIA = 120
MIN_AUMENTO_ENTRENAMIENTO = 3
MAX_AUMENTO_ENTRENAMIENTO = 12  
AUMENTAR_VIDA_PLANTA = 25
AUMENTAR_ATAQUE_FUEGO = 15
AUMENTAR_VELOCIDAD_AGUA = 20
GASTO_ENERGIA_BAYA = 3
GASTO_ENERGIA_POCION = 4
GASTO_ENERGIA_CARAMELO = 5
PROB_EXITO_BAYA = 0.8
PROB_EXITO_POCION = 0.75
PROB_EXITO_CARAMELO = 0.8
AUMENTO_DEFENSA = 6
RUTA_PROG = os.path.join("programones.csv")
RUTA_OBJ = os.path.join("objetos.csv")
RUTA_ENTR = os.path.join("entrenadores.csv")
